apiVersion: v1

kind: Pod

metadata:

  name: redis-pod

spec:

  containers:

  - name: redis

    image: redis:5.0.4

    command:

      - redis-server

      - "/redis-master/redis.conf"

    env:

    - name: MASTER

      value: "true"

    ports:

    - containerPort: 6379

    resources:

      limits:

        cpu: "200m"
        memory: "200Mi"

    volumeMounts:

    - mountPath: var/lib/redis-pod
      name: data

    - mountPath: /redis-master

      name: config

  volumes:

    - name: data

      path: redis

    - name: config

      configMap:

        name: example-redis-config
        items:

        - key: redis-config

          path: redis.confg